development:
  adapter: postgresql
  encoding: unicode
  database: club_manager_development
  pool: 5
  username: tadpreston
  password: nov8ordie
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: club_manager_test
  pool: 5
  username: postgres
