development_postgresql:
  adapter: postgresql
  encoding: unicode
  database: club_manager_development
  pool: 5
  username: tadpreston
  password: nov8ordie
  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: clubdb
  pool: 5
  username: clubawuser
  password: nov8ordie
  host: clubdbinstance.ciruh58wjbko.us-west-2.rds.amazonaws.com
  port: 3306

test:
  adapter: postgresql
  encoding: unicode
  database: club_manager_test
  pool: 5
  username: postgres
