development:
  adapter: postgresql
  encoding: utf8
  database: club_manager_development
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: club_manager_test
  pool: 5
  username:
  password:
  host: localhost
