development:
  adapter: postgresql
  encoding: utf8
  database: clubmanager
  pool: 5
  username: postgres
  password: passwordpa
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: clubmanager
  pool: 5
  username: postgres
  password: passwordpa
  host: localhost
