require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MonthlySummariesController do

  # This should return the minimal set of attributes required to create a valid
  # MonthlySummary. As you add validations to MonthlySummary, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MonthlySummariesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all monthly_summaries as @monthly_summaries" do
      monthly_summary = MonthlySummary.create! valid_attributes
      get :index, {}, valid_session
      assigns(:monthly_summaries).should eq([monthly_summary])
    end
  end

  describe "GET show" do
    it "assigns the requested monthly_summary as @monthly_summary" do
      monthly_summary = MonthlySummary.create! valid_attributes
      get :show, {:id => monthly_summary.to_param}, valid_session
      assigns(:monthly_summary).should eq(monthly_summary)
    end
  end

  describe "GET new" do
    it "assigns a new monthly_summary as @monthly_summary" do
      get :new, {}, valid_session
      assigns(:monthly_summary).should be_a_new(MonthlySummary)
    end
  end

  describe "GET edit" do
    it "assigns the requested monthly_summary as @monthly_summary" do
      monthly_summary = MonthlySummary.create! valid_attributes
      get :edit, {:id => monthly_summary.to_param}, valid_session
      assigns(:monthly_summary).should eq(monthly_summary)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MonthlySummary" do
        expect {
          post :create, {:monthly_summary => valid_attributes}, valid_session
        }.to change(MonthlySummary, :count).by(1)
      end

      it "assigns a newly created monthly_summary as @monthly_summary" do
        post :create, {:monthly_summary => valid_attributes}, valid_session
        assigns(:monthly_summary).should be_a(MonthlySummary)
        assigns(:monthly_summary).should be_persisted
      end

      it "redirects to the created monthly_summary" do
        post :create, {:monthly_summary => valid_attributes}, valid_session
        response.should redirect_to(MonthlySummary.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved monthly_summary as @monthly_summary" do
        # Trigger the behavior that occurs when invalid params are submitted
        MonthlySummary.any_instance.stub(:save).and_return(false)
        post :create, {:monthly_summary => {}}, valid_session
        assigns(:monthly_summary).should be_a_new(MonthlySummary)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MonthlySummary.any_instance.stub(:save).and_return(false)
        post :create, {:monthly_summary => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested monthly_summary" do
        monthly_summary = MonthlySummary.create! valid_attributes
        # Assuming there are no other monthly_summaries in the database, this
        # specifies that the MonthlySummary created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MonthlySummary.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => monthly_summary.to_param, :monthly_summary => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested monthly_summary as @monthly_summary" do
        monthly_summary = MonthlySummary.create! valid_attributes
        put :update, {:id => monthly_summary.to_param, :monthly_summary => valid_attributes}, valid_session
        assigns(:monthly_summary).should eq(monthly_summary)
      end

      it "redirects to the monthly_summary" do
        monthly_summary = MonthlySummary.create! valid_attributes
        put :update, {:id => monthly_summary.to_param, :monthly_summary => valid_attributes}, valid_session
        response.should redirect_to(monthly_summary)
      end
    end

    describe "with invalid params" do
      it "assigns the monthly_summary as @monthly_summary" do
        monthly_summary = MonthlySummary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MonthlySummary.any_instance.stub(:save).and_return(false)
        put :update, {:id => monthly_summary.to_param, :monthly_summary => {}}, valid_session
        assigns(:monthly_summary).should eq(monthly_summary)
      end

      it "re-renders the 'edit' template" do
        monthly_summary = MonthlySummary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MonthlySummary.any_instance.stub(:save).and_return(false)
        put :update, {:id => monthly_summary.to_param, :monthly_summary => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested monthly_summary" do
      monthly_summary = MonthlySummary.create! valid_attributes
      expect {
        delete :destroy, {:id => monthly_summary.to_param}, valid_session
      }.to change(MonthlySummary, :count).by(-1)
    end

    it "redirects to the monthly_summaries list" do
      monthly_summary = MonthlySummary.create! valid_attributes
      delete :destroy, {:id => monthly_summary.to_param}, valid_session
      response.should redirect_to(monthly_summaries_url)
    end
  end

end
